### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by KomuSei** [HenryLulu/video-to-doc-ocr#2]
root@:~# python3 index.py
Traceback (most recent call last):
  File "index.py", line 1, in <module>
    import getframe
  File "/root/getframe.py", line 31
    print c
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c)?

windows的Ubuntu子系统运行报错，windows搭建python环境也会报同样的错

**Comment by RockZhou8** [comment]
```
PS C:\python\video-to-text-ocr-demo-master> python index.py
Traceback (most recent call last):
  File "index.py", line 1, in <module>
    import getframe
  File "C:\python\video-to-text-ocr-demo-master\getframe.py", line 31
    print c
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c)?
PS C:\python\video-to-text-ocr-demo-master>
```
同样的问题，你解决了吗
